[server]
host = 'localhost'
port = 8080
debug = true
reloader = true

[static]  # optional
root = 'static'  # local path to which requests to /static map

[db]
url = 'postgres://user:password@127.0.0.1:5432/database'

[keys]
cookie = 'any random string'
recovery = 'any random string'
mail_confirm = 'any random string'

[vk]
client_id = 11111111
redirect_uri = 'http://localhost:8080/login/vk'
client_secret = 'abcdefg'
auth_url = 'http://oauth.vk.com/authorize'
token_url = 'https://oauth.vk.com/access_token'
info_url = 'https://api.vk.com/method/users.get'

[reg]
secret = 'ABCDabcdABCDabcdABCDabcdABCDabcdABCDabcd'
sitekey = 'efghIJKLefghIJKLefghIJKLefghIJKLefghIJKL'
reg_url = 'https://www.google.com/recaptcha/api/siteverify'
min_login_size = 4
max_login_size = 20
min_password_size = 6
max_password_size = 1000
min_name_size = 4
max_name_size = 1000
min_surname_size = 4
max_surname_size = 1000
min_email_size = 3
max_email_size = 254
min_school_size = 4
max_school_size = 1000
min_city_size = 4
max_city_size = 1000
min_clas_size = 1
max_clas_size = 100

[contacts]
support_email = 'test@test.com'
vk_link = 'https://vk.com/kvantland'
tg_link = 'https://t.me/kvantland'
youtube_link = 'https://www.youtube.com/@Kvantland'

[xhr]
dead_step = 1000

[recovery]
localhost = 'localhost'
acc_confirm_uri = 'http://localhost:8080/acc_confirm'
reg_confirm_uri = 'http://localhost:8080/reg_confirm'
redirect_uri = 'http://localhost:8080/pw_recovery/new_password'
host = 'smtp.go1.unisender.ru'
port = 465
login = '11111111'
password = ''
sender = 'noreply@kvantland.ru'
send_again = 60

[tournament]
version = 1
mode = 'public'

[mail_check]
allowed_period = 86400
allowed_amount = 10